version: "3.9"
services:
  event-data-pipeline:
    image: youngstone89/event-data-pipeline:latest
    environment:
      - EDP_ENABLE_DEBUG_LOGGING=true
      - EDP_CONFIG=configs/config.docker_compose.kafka.yaml
    volumes:
      - ../configs:/app/configs
    networks:
      - edp-net
    depends_on:
      - kafka
      - elasticsearch
networks:
  edp-net:
    driver: bridge